name: Build

on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
      - "release/*"
  pull_request:
    branches:
      - "main"
      - "release/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          servers: |
            [{
                "id": "github",
                "url": "https://maven.pkg.github.com/ArtemGet/*",
                "username": "${{ secrets.USER_PACKAGE_READ }}",
                "password": "${{ secrets.TOKEN_PACKAGE_READ }}"
            }]
      - name: Build with Maven
        run: mvn clean install -Pqulice --batch-mode --update-snapshots
